name: Build project

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      ASAN_OPTIONS: detect_odr_violation=0
    steps:
      - uses: actions/checkout@v4
      - name: Installing cmake...
        run: sudo apt install cmake
      - name: Building...
        run: |
          cd src
          mkdir .build && cd .build
          cmake ..
          set ASAN_OPTIONS=detect_odr_violation=0
          make -j
      - name: Testing...
        run: |
          cd src/.build
          set ASAN_OPTIONS=detect_odr_violation=0
          ./HSE_SD_tests

      
