name: Build project

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing cmake...
        run: sudo apt install cmake
      - name: Building...
        run: mkdir build && |
          cd build && |
          cmake ../src |
          cmake --build .

      
