name: Build project

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      ASAN_OPTIONS: alloc_dealloc_mismatch=0
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install cmake -y
        
      - name: Install dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
      
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Build the project
        run: |
          cd src
          mkdir .build && cd .build
          cmake ..
          ${{ if eq(matrix.os, 'windows-latest') }}: |
            set ASAN_OPTIONS=detect_odr_violation=0
            cmake --build . --config Release -- /m
          ${{ else }}: |
            make -j

      - name: Run tests
        run: |
          cd src/.build
          ${{ if eq(matrix.os, 'windows-latest') }}: |
            set ASAN_OPTIONS=detect_odr_violation=0
            .\Release\HSE_SD_tests.exe
          ${{ else }}: |
            export ASAN_OPTIONS=detect_odr_violation=0
            ./HSE_SD_tests